import type { Metadata } from "next";
import "./styles/globals.css";
import { NuzlockeProvider } from "@/hooks/useNuzlocke";
import { WindowSizeProvider } from "@/hooks/useWindowSize";
import { PokedexProvider } from "@/hooks/usePokedex";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import { ControllerProvider } from "@/hooks/useController";

export const metadata: Metadata = {
  title: "Pokémon Tools",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <NuzlockeProvider>
        <WindowSizeProvider>
          <PokedexProvider>
            <ControllerProvider>
              <html lang="en">
                {/* <Head>
              <script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
              ></script>
              <script>
              {`
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                
                gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}')
                `}
                </script>
                <title>Pokémon Tools</title>
                </Head> */}
                <body>
                  <main>
                    <Nav />
                    {children}
                    <Footer />
                  </main>
                </body>
              </html>
            </ControllerProvider>
          </PokedexProvider>
        </WindowSizeProvider>
      </NuzlockeProvider>
    </SessionProvider>
  );
}
